image: registry.csc.sibsutis.ru/ci/git-clang-format:latest

stages:
  - build
  - check-format
  - test

build:
  stage: build
  script:
    - make

check-format:
  stage: check-format
  script:
  - find . -type f -name *.[ch] ! -name '*ctest.h' | xargs clang-format --style GNU -i --verbose
  - git diff --exit-code

test:
  stage: test
  script:
    - make test
